// ... existing imports and code ...
// Removed unused variable:
// const sectionItems = segments[0] && SECTIONS[segments[0]] ? (SECTIONS[segments[0]] as any[]) : [];

// ... rest of the code remains unchanged ...
