import type { LucideIcon } from 'lucide-react';
import {
  HomeIcon,
  BookOpenIcon,
  ShieldAlertIcon,
  DollarSignIcon,
  UsersIcon,
  BriefcaseIcon,
  TrendingUpIcon,
  FileTextIcon,
  BarChart2Icon,
} from 'lucide-react';

export interface NavItem {
  title: string;
  href?: string;
  icon?: LucideIcon;
  slug?: string;
  label?: string;
  children?: NavItem[];
}

export interface Section {
  title: string;
  items: NavItem[];
}

export const MAIN_NAV_ITEMS: NavItem[] = [
  {
    title: 'Dashboard',
    href: '/dashboard',
    icon: HomeIcon,
    slug: 'dashboard',
    label: 'Dashboard',
  },
  {
    title: 'Training & Development',
    href: '/training',
    icon: BookOpenIcon,
    slug: 'training',
    label: 'Training & Development',
  },
  {
    title: 'Safety & WHS',
    href: '/safety',
    icon: ShieldAlertIcon,
    slug: 'safety',
    label: 'Safety & WHS',
  },
  {
    title: 'Payroll & Finance',
    href: '/payroll',
    icon: DollarSignIcon,
    slug: 'payroll',
    label: 'Payroll & Finance',
  },
  {
    title: 'Human Resources',
    href: '/hr',
    icon: UsersIcon,
    slug: 'hr',
    label: 'Human Resources',
  },
  {
    title: 'Client Management',
    href: '/clients',
    icon: BriefcaseIcon,
    slug: 'clients',
    label: 'Client Management',
  },
  {
    title: 'Marketing & Sales',
    href: '/marketing',
    icon: TrendingUpIcon,
    slug: 'marketing',
    label: 'Marketing & Sales',
  },
  {
    title: 'Compliance & Quality',
    href: '/compliance',
    icon: FileTextIcon,
    slug: 'compliance',
    label: 'Compliance & Quality',
  },
  {
    title: 'Reports & Analytics',
    href: '/reports',
    icon: BarChart2Icon,
    slug: 'reports',
    label: 'Reports & Analytics',
  },
];

export const SECTIONS: Record<string, NavItem[]> = {
  dashboard: [
    { title: 'Overview', href: '/dashboard/overview', label: 'Overview' },
    { title: 'Quick Actions', href: '/dashboard/quick-actions', label: 'Quick Actions' },
    { title: 'Recent Activities', href: '/dashboard/recent-activities', label: 'Recent Activities' },
    { title: 'Notifications', href: '/dashboard/notifications', label: 'Notifications' },
    { title: 'Alerts & Reminders', href: '/dashboard/alerts-reminders', label: 'Alerts & Reminders' },
    { title: 'Key Metrics', href: '/dashboard/key-metrics', label: 'Key Metrics' },
    { title: 'Task List', href: '/dashboard/task-list', label: 'Task List' },
    { title: 'Calendar View', href: '/dashboard/calendar', label: 'Calendar View' },
  ],
  training: [
    { title: 'Apprentices', href: '/training/apprentices', label: 'Apprentices' },
    { title: 'Trainees', href: '/training/trainees', label: 'Trainees' },
    { title: 'Course Catalog', href: '/training/courses', label: 'Course Catalog' },
    { title: 'Training Calendar', href: '/training/calendar', label: 'Training Calendar' },
    { title: 'Assessments', href: '/training/assessments', label: 'Assessments' },
    { title: 'Certifications', href: '/training/certifications', label: 'Certifications' },
    { title: 'Skills Matrix', href: '/training/skills-matrix', label: 'Skills Matrix' },
    { title: 'Training Records', href: '/training/records', label: 'Training Records' },
    { title: 'Learning Plans', href: '/training/learning-plans', label: 'Learning Plans' },
    { title: 'Training Resources', href: '/training/resources', label: 'Training Resources' },
    { title: 'Competency Tracking', href: '/training/competency-tracking', label: 'Competency Tracking' },
    { title: 'Qualification Framework', href: '/training/qualification-framework', label: 'Qualification Framework' },
    { title: 'Training Providers', href: '/training/providers', label: 'Training Providers' },
    { title: 'Workshop Schedule', href: '/training/workshops', label: 'Workshop Schedule' },
  ],
  safety: [
    { title: 'Incident Reports', href: '/safety/incident-reports', label: 'Incident Reports' },
    { title: 'Hazard Register', href: '/safety/hazard-register', label: 'Hazard Register' },
    { title: 'Safety Audits', href: '/safety/audits', label: 'Safety Audits' },
    { title: 'Risk Assessments', href: '/safety/risk-assessments', label: 'Risk Assessments' },
    { title: 'Safety Documents', href: '/safety/documents', label: 'Safety Documents' },
    { title: 'PPE Management', href: '/safety/ppe-management', label: 'PPE Management' },
    { title: 'Safety Training', href: '/safety/training', label: 'Safety Training' },
    { title: 'Emergency Procedures', href: '/safety/emergency-procedures', label: 'Emergency Procedures' },
    { title: 'Safety Meetings', href: '/safety/meetings', label: 'Safety Meetings' },
    { title: 'Inspection Reports', href: '/safety/inspections', label: 'Inspection Reports' },
    { title: 'Safety Statistics', href: '/safety/statistics', label: 'Safety Statistics' },
    { title: 'Compliance Calendar', href: '/safety/compliance-calendar', label: 'Compliance Calendar' },
    { title: 'Safety Alerts', href: '/safety/alerts', label: 'Safety Alerts' },
    { title: 'Return to Work', href: '/safety/return-to-work', label: 'Return to Work' },
  ],
  payroll: [
    { title: 'Payroll Processing', href: '/payroll/processing', label: 'Payroll Processing' },
    { title: 'Timesheets', href: '/payroll/timesheets', label: 'Timesheets' },
    { title: 'Award Rates', href: '/payroll/award-rates', label: 'Award Rates' },
    { title: 'Allowances', href: '/payroll/allowances', label: 'Allowances' },
    { title: 'Deductions', href: '/payroll/deductions', label: 'Deductions' },
    { title: 'Superannuation', href: '/payroll/superannuation', label: 'Superannuation' },
    { title: 'Tax Management', href: '/payroll/tax-management', label: 'Tax Management' },
    { title: 'Expense Claims', href: '/payroll/expense-claims', label: 'Expense Claims' },
    { title: 'Invoicing', href: '/payroll/invoicing', label: 'Invoicing' },
    { title: 'Payment History', href: '/payroll/payment-history', label: 'Payment History' },
    { title: 'Funding Claims', href: '/payroll/funding-claims', label: 'Funding Claims' },
    { title: 'Budget Tracking', href: '/payroll/budget-tracking', label: 'Budget Tracking' },
    { title: 'Financial Reports', href: '/payroll/financial-reports', label: 'Financial Reports' },
    { title: 'Bank Reconciliation', href: '/payroll/bank-reconciliation', label: 'Bank Reconciliation' },
    { title: 'Cost Centers', href: '/payroll/cost-centers', label: 'Cost Centers' },
  ],
  hr: [
    { title: 'Employees', href: '/hr/employees', label: 'Employees' },
    { title: 'Candidates', href: '/hr/candidates', label: 'Candidates' },
    { title: 'Job Postings', href: '/hr/job-postings', label: 'Job Postings' },
    { title: 'Recruitment', href: '/hr/recruitment', label: 'Recruitment' },
    { title: 'Onboarding', href: '/hr/onboarding', label: 'Onboarding' },
    { title: 'Performance Reviews', href: '/hr/performance-reviews', label: 'Performance Reviews' },
    { title: 'Leave Management', href: '/hr/leave-management', label: 'Leave Management' },
    { title: 'Training Records', href: '/hr/training-records', label: 'Training Records' },
    { title: 'Employee Documents', href: '/hr/documents', label: 'Employee Documents' },
    { title: 'Benefits Administration', href: '/hr/benefits', label: 'Benefits Administration' },
    { title: 'Disciplinary Actions', href: '/hr/disciplinary-actions', label: 'Disciplinary Actions' },
    { title: 'Exit Management', href: '/hr/exit-management', label: 'Exit Management' },
    { title: 'HR Reports', href: '/hr/reports', label: 'HR Reports' },
    { title: 'Organization Chart', href: '/hr/org-chart', label: 'Organization Chart' },
    { title: 'Position Management', href: '/hr/position-management', label: 'Position Management' },
    { title: 'Succession Planning', href: '/hr/succession-planning', label: 'Succession Planning' },
  ],
  clients: [
    { title: 'Client Directory', href: '/clients/directory', label: 'Client Directory' },
    { title: 'Host Employers', href: '/clients/host-employers', label: 'Host Employers' },
    { title: 'Client Contacts', href: '/clients/contacts', label: 'Client Contacts' },
    { title: 'Account Management', href: '/clients/account-management', label: 'Account Management' },
    { title: 'Service Agreements', href: '/clients/service-agreements', label: 'Service Agreements' },
    { title: 'Client Communications', href: '/clients/communications', label: 'Client Communications' },
    { title: 'Visit Reports', href: '/clients/visit-reports', label: 'Visit Reports' },
    { title: 'Client Requirements', href: '/clients/requirements', label: 'Client Requirements' },
    { title: 'Placement History', href: '/clients/placement-history', label: 'Placement History' },
    { title: 'Client Documents', href: '/clients/documents', label: 'Client Documents' },
    { title: 'Feedback & Surveys', href: '/clients/feedback-surveys', label: 'Feedback & Surveys' },
    { title: 'Support Tickets', href: '/clients/support-tickets', label: 'Support Tickets' },
    { title: 'Client Portal', href: '/clients/portal', label: 'Client Portal' },
    { title: 'Opportunity Pipeline', href: '/clients/opportunity-pipeline', label: 'Opportunity Pipeline' },
    { title: 'Client Analytics', href: '/clients/analytics', label: 'Client Analytics' },
  ],
  marketing: [
    { title: 'Campaigns', href: '/marketing/campaigns', label: 'Campaigns' },
    { title: 'Lead Management', href: '/marketing/lead-management', label: 'Lead Management' },
    { title: 'Sales Pipeline', href: '/marketing/sales-pipeline', label: 'Sales Pipeline' },
    { title: 'Marketing Calendar', href: '/marketing/calendar', label: 'Marketing Calendar' },
    { title: 'Email Marketing', href: '/marketing/email', label: 'Email Marketing' },
    { title: 'Social Media', href: '/marketing/social-media', label: 'Social Media' },
    { title: 'Website Analytics', href: '/marketing/website-analytics', label: 'Website Analytics' },
    { title: 'Event Management', href: '/marketing/events', label: 'Event Management' },
    { title: 'Marketing Materials', href: '/marketing/materials', label: 'Marketing Materials' },
    { title: 'Competitor Analysis', href: '/marketing/competitor-analysis', label: 'Competitor Analysis' },
    { title: 'Market Research', href: '/marketing/market-research', label: 'Market Research' },
    { title: 'ROI Tracking', href: '/marketing/roi-tracking', label: 'ROI Tracking' },
    { title: 'Campaign Analytics', href: '/marketing/campaign-analytics', label: 'Campaign Analytics' },
    { title: 'Brand Assets', href: '/marketing/brand-assets', label: 'Brand Assets' },
  ],
  compliance: [
    { title: 'Compliance Dashboard', href: '/compliance/dashboard', label: 'Compliance Dashboard' },
    { title: 'Audit Management', href: '/compliance/audits', label: 'Audit Management' },
    { title: 'Document Control', href: '/compliance/document-control', label: 'Document Control' },
    { title: 'Quality Metrics', href: '/compliance/quality-metrics', label: 'Quality Metrics' },
    { title: 'Standards & Regulations', href: '/compliance/standards-regulations', label: 'Standards & Regulations' },
    { title: 'Compliance Training', href: '/compliance/training', label: 'Compliance Training' },
    { title: 'Corrective Actions', href: '/compliance/corrective-actions', label: 'Corrective Actions' },
    { title: 'Policy Management', href: '/compliance/policy-management', label: 'Policy Management' },
    { title: 'License Management', href: '/compliance/license-management', label: 'License Management' },
    { title: 'Compliance Reports', href: '/compliance/reports', label: 'Compliance Reports' },
    { title: 'Quality Reviews', href: '/compliance/quality-reviews', label: 'Quality Reviews' },
    { title: 'Risk Register', href: '/compliance/risk-register', label: 'Risk Register' },
    { title: 'Compliance Calendar', href: '/compliance/compliance-calendar', label: 'Compliance Calendar' },
    { title: 'Regulatory Updates', href: '/compliance/regulatory-updates', label: 'Regulatory Updates' },
  ],
  reports: [
    { title: 'Standard Reports', href: '/reports/standard', label: 'Standard Reports' },
    { title: 'Custom Reports', href: '/reports/custom', label: 'Custom Reports' },
    { title: 'Analytics Dashboard', href: '/reports/analytics-dashboard', label: 'Analytics Dashboard' },
    { title: 'KPI Tracking', href: '/reports/kpi-tracking', label: 'KPI Tracking' },
    { title: 'Performance Metrics', href: '/reports/performance-metrics', label: 'Performance Metrics' },
    { title: 'Financial Reports', href: '/reports/financial', label: 'Financial Reports' },
    { title: 'Training Reports', href: '/reports/training', label: 'Training Reports' },
    { title: 'Safety Reports', href: '/reports/safety', label: 'Safety Reports' },
    { title: 'Client Reports', href: '/reports/clients', label: 'Client Reports' },
    { title: 'HR Reports', href: '/reports/hr', label: 'HR Reports' },
    { title: 'Compliance Reports', href: '/reports/compliance', label: 'Compliance Reports' },
    { title: 'Export Center', href: '/reports/export', label: 'Export Center' },
    { title: 'Report Scheduler', href: '/reports/scheduler', label: 'Report Scheduler' },
    { title: 'Data Visualization', href: '/reports/data-visualization', label: 'Data Visualization' },
    { title: 'Trend Analysis', href: '/reports/trend-analysis', label: 'Trend Analysis' },
  ],
};
