name: Deployment Notifications

on:
  deployment_status:
    branches:
      - master
      - main
    types: [created, started, completed, error]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Deployment Status
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'deployments'  # Replace with your channel ID
          slack-message: |
            Deployment Status: ${{ github.event.deployment_status.state }}
            Environment: ${{ github.event.deployment.environment }}
            URL: ${{ github.event.deployment_status.target_url }}
            Description: ${{ github.event.deployment_status.description }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
