---
name: Lint Code Base

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Enable specific linters
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_CSS: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_ENV: true
          VALIDATE_HTML: true
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_TYPESCRIPT_STANDARD: true
          VALIDATE_SECURITY: true
          # Use project's existing configs
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          # Enable prettier formatting validation
          VALIDATE_TYPESCRIPT_PRETTIER: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_YAML_PRETTIER: true
          # Enable GitHub Actions features
          ENABLE_GITHUB_ACTIONS_GROUP_TITLE: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
